export const FETCH_COVID_FAILURE = "FETCH_COVID_FAILURE";
export const FETCH_COVID_REQUEST = "FETCH_COVID_REQUEST";
export const FETCH_COVID_SUCCESS = "FETCH_COVID_SUCCESS";

export const FETCH_TOTAL_FAILURE = "FETCH_TOTAL_FAILURE";
export const FETCH_TOTAL_REQUEST = "FETCH_TOTAL_REQUEST";
export const FETCH_TOTAL_SUCCESS = "FETCH_TOTAL_SUCCESS";
